/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Alunos: () => import('#controllers/alunos_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Bases: () => import('#controllers/bases_controller'),
  Conta: () => import('#controllers/conta_controller'),
  Cursos: () => import('#controllers/cursos_controller'),
  Disciplinas: () => import('#controllers/disciplinas_controller'),
  interfaces: {
    BaseCrudInterface: () => import('#controllers/interfaces/base_crud_interface'),
    PolicyInterface: () => import('#controllers/interfaces/policy_interface'),
    ValidatorInerface: () => import('#controllers/interfaces/validator_inerface'),
  },
  Matriculas: () => import('#controllers/matriculas_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
